batch_size: 1
nstacks: 8
output_dim: 24
nfeat: 512
nlow: 3
dropout_rate: 0.8
optimizer: 'rmsprop'
learning_rate: 0.00025
end_learning_rate: 0.00001
learning_rate_decay_type: 'exponential'
num_epochs_per_decay: 10
learning_rate_decay_factor: 0.9
num_clones: 1
max_epochs: 400
hm_size: 64
input_size: 256
joints:
- neckline_left
- neckline_right
- center_front
- shoulder_left
- shoulder_right
- armpit_left
- armpit_right
- waistline_left
- waistline_right
- cuff_left_in
- cuff_left_out
- cuff_right_in
- cuff_right_out
- top_hem_left
- top_hem_right
- waistband_left
- waistband_right
- hemline_left
- hemline_right
- crotch
- bottom_left_in
- bottom_left_out
- bottom_right_in
- bottom_right_out
thresh: 0.5