batch_size: 1
nstacks: 4
output_dim: 5
nfeat: 512
nlow: 2
dropout_rate: 0.8
optimizer: 'rmsprop'
learning_rate: 0.00025
end_learning_rate: 0.00001
learning_rate_decay_type: 'exponential'
num_epochs_per_decay: 10
learning_rate_decay_factor: 0.9
max_epochs: 400
hm_size: 32
input_size: 64
joints:
- lefteye
- righteye
- nose
- leftmouth
- rightmouth
thresh: 0.2