InferIcnet:
 name: 'Inference'
 dataset:
  name: 'portrait'
 model:
  clone_on_cpu: false
  num_clones: 1
  batch_size: 1
  num_classes: 2
  checkpoint_path: '/home/mi/model/TrainingIcnet/2017-08-22-10-59-20/alpha_train_421600.ckpt'

EvaluationIcnet:
 name: 'Evaluating'
 task:
  type: 'SEGMENTATION'
  class_label: [1]
 measure:
 - 'PixelAccuracy'
 - 'MeanAccuracy'
 - 'MeanIOU'
 - 'FrequencyWeightedIOU'
 - 'MeanIOUBoundary'
 input-bind:
 - 'InferIcnet'