crop_size: 256
original_height: 512
original_width: 512
scale_size: 286
max_epochs: 200
batch_size: 1
ngf: 64
ndf: 64
l1_weight: 100.0
gan_weight: 1.0
discriminator:
 lr: 0.0002
 beta1: 0.5
optimizer: 'adam'
adam_beta1: 0.5
learning_rate: 0.0002
end_learning_rate: 0.0001
input_dir: '/home/mi/combined/train'